/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/admin/models/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * Update Model
         * @description Update a model (admin only)
         */
        put: operations["update_model"];
        post?: never;
        /**
         * Delete Model
         * @description Delete a model (admin only)
         */
        delete: operations["delete_model"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/providers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List All Providers
         * @description List all provider configurations (admin only)
         */
        get: operations["list_all_providers"];
        put?: never;
        /**
         * Create Provider
         * @description Create a new provider configuration (admin only)
         */
        post: operations["create_provider"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/providers/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * Update Provider
         * @description Update a provider configuration (admin only)
         */
        put: operations["update_provider"];
        post?: never;
        /**
         * Delete Provider
         * @description Delete a provider configuration (admin only)
         */
        delete: operations["delete_provider"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/providers/{provider_id}/models": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Provider Models
         * @description List models for a provider (admin only)
         */
        get: operations["list_provider_models"];
        put?: never;
        /**
         * Create Model
         * @description Create a model for a provider (admin only)
         */
        post: operations["create_model"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Users
         * @description Get all users (admin only)
         */
        get: operations["list_users"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/users/{user_id}/groups": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * Update User Groups
         * @description Update user groups (admin only)
         */
        put: operations["update_user_groups"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/users/{user_id}/usage": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Usage Stats
         * @description Get usage statistics for a user
         */
        get: operations["get_usage_stats"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api-keys": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Api Keys
         * @description List user's API keys
         */
        get: operations["list_api_keys"];
        put?: never;
        /**
         * Create Api Key
         * @description Create a new API key
         */
        post: operations["create_api_key"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api-keys/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Revoke Api Key
         * @description Revoke an API key
         */
        delete: operations["revoke_api_key"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Login
         * @description Login with email and password
         */
        post: operations["login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Logout
         * @description Logout - invalidate token (stateless, just returns success)
         */
        post: operations["logout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Refresh Token
         * @description Refresh token - generate new access token
         */
        post: operations["refresh_token"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Register
         * @description Register a new user
         */
        post: operations["register"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/validate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Validate Token
         * @description Validate token - returns user info if token is valid
         */
        get: operations["validate_token"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health Check
         * @description Health check endpoint (no auth required)
         */
        get: operations["health_check"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/models": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Available Models
         * @description List models available to the current user based on their user_groups
         */
        get: operations["list_available_models"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/usage": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Usage
         * @description Get usage summary for the authenticated user
         */
        get: operations["get_usage"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/usage/stats": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Usage Stats
         * @description Get dashboard stats for the authenticated user
         */
        get: operations["get_usage_stats"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/user/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Current User
         * @description Get current user info
         */
        get: operations["get_current_user"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/user/profile": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Current User
         * @description Get current user info
         */
        get: operations["get_current_user"];
        /**
         * Update Profile
         * @description Update user profile
         */
        put: operations["update_profile"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: never;
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    update_model: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        /** @description Request to update a model */
        requestBody: {
            content: {
                "application/json": {
                    display_name?: string | null;
                    /** Format: decimal */
                    input_cost_per_1k?: string | null;
                    is_active?: boolean | null;
                    max_context?: number | null;
                    /** Format: decimal */
                    output_cost_per_1k?: string | null;
                    supports_tools?: boolean | null;
                    supports_vision?: boolean | null;
                };
            };
        };
        responses: {
            /** @description default return */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        created_at: string;
                        display_name?: string | null;
                        /** Format: uuid */
                        id: string;
                        /** Format: decimal */
                        input_cost_per_1k?: string | null;
                        is_active: boolean;
                        max_context?: number | null;
                        model_id: string;
                        /** Format: decimal */
                        output_cost_per_1k?: string | null;
                        /** Format: uuid */
                        provider_config_id: string;
                        supports_tools: boolean;
                        supports_vision: boolean;
                        updated_at: string;
                    };
                };
            };
        };
    };
    delete_model: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description default return */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": Record<string, never>;
                };
            };
        };
    };
    list_all_providers: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description default return */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        allowed_groups: string[];
                        base_url?: string | null;
                        created_at: string;
                        /** Format: uuid */
                        id: string;
                        is_active: boolean;
                        /** Format: decimal */
                        monthly_quota?: string | null;
                        name: string;
                        priority: number;
                        provider_type: string;
                        rate_limit?: number | null;
                        updated_at: string;
                        /** Format: decimal */
                        used_quota: string;
                    }[];
                };
            };
        };
    };
    create_provider: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    allowed_groups?: string[] | null;
                    api_key: string;
                    base_url?: string | null;
                    /** Format: decimal */
                    monthly_quota?: string | null;
                    name: string;
                    priority?: number | null;
                    provider_type: string;
                    rate_limit?: number | null;
                };
            };
        };
        responses: {
            /** @description default return */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        allowed_groups: string[];
                        base_url?: string | null;
                        created_at: string;
                        /** Format: uuid */
                        id: string;
                        is_active: boolean;
                        /** Format: decimal */
                        monthly_quota?: string | null;
                        name: string;
                        priority: number;
                        provider_type: string;
                        rate_limit?: number | null;
                        updated_at: string;
                        /** Format: decimal */
                        used_quota: string;
                    };
                };
            };
        };
    };
    update_provider: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    allowed_groups?: string[] | null;
                    api_key?: string | null;
                    base_url?: string | null;
                    is_active?: boolean | null;
                    /** Format: decimal */
                    monthly_quota?: string | null;
                    name?: string | null;
                    priority?: number | null;
                    rate_limit?: number | null;
                };
            };
        };
        responses: {
            /** @description default return */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        allowed_groups: string[];
                        base_url?: string | null;
                        created_at: string;
                        /** Format: uuid */
                        id: string;
                        is_active: boolean;
                        /** Format: decimal */
                        monthly_quota?: string | null;
                        name: string;
                        priority: number;
                        provider_type: string;
                        rate_limit?: number | null;
                        updated_at: string;
                        /** Format: decimal */
                        used_quota: string;
                    };
                };
            };
        };
    };
    delete_provider: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description default return */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": Record<string, never>;
                };
            };
        };
    };
    list_provider_models: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                provider_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description default return */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        created_at: string;
                        display_name?: string | null;
                        /** Format: uuid */
                        id: string;
                        /** Format: decimal */
                        input_cost_per_1k?: string | null;
                        is_active: boolean;
                        max_context?: number | null;
                        model_id: string;
                        /** Format: decimal */
                        output_cost_per_1k?: string | null;
                        /** Format: uuid */
                        provider_config_id: string;
                        supports_tools: boolean;
                        supports_vision: boolean;
                        updated_at: string;
                    }[];
                };
            };
        };
    };
    create_model: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                provider_id: string;
            };
            cookie?: never;
        };
        /** @description Request to create a model */
        requestBody: {
            content: {
                "application/json": {
                    display_name?: string | null;
                    /** Format: decimal */
                    input_cost_per_1k?: string | null;
                    max_context?: number | null;
                    model_id: string;
                    /** Format: decimal */
                    output_cost_per_1k?: string | null;
                    supports_tools?: boolean | null;
                    supports_vision?: boolean | null;
                };
            };
        };
        responses: {
            /** @description default return */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        created_at: string;
                        display_name?: string | null;
                        /** Format: uuid */
                        id: string;
                        /** Format: decimal */
                        input_cost_per_1k?: string | null;
                        is_active: boolean;
                        max_context?: number | null;
                        model_id: string;
                        /** Format: decimal */
                        output_cost_per_1k?: string | null;
                        /** Format: uuid */
                        provider_config_id: string;
                        supports_tools: boolean;
                        supports_vision: boolean;
                        updated_at: string;
                    };
                };
            };
        };
    };
    list_users: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description default return */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        created_at: string;
                        email: string;
                        /** Format: uuid */
                        id: string;
                        is_admin: boolean;
                        user_groups: string[];
                        username: string;
                    }[];
                };
            };
        };
    };
    update_user_groups: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                user_id: string;
            };
            cookie?: never;
        };
        /** @description Request to update user groups */
        requestBody: {
            content: {
                "application/json": {
                    user_groups: string[];
                };
            };
        };
        responses: {
            /** @description default return */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        created_at: string;
                        email: string;
                        /** Format: uuid */
                        id: string;
                        is_admin: boolean;
                        user_groups: string[];
                        username: string;
                    };
                };
            };
        };
    };
    get_usage_stats: {
        parameters: {
            query?: {
                start?: string | null;
                end?: string | null;
            };
            header?: never;
            path: {
                user_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description default return */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        by_model: {
                            completion_tokens: number;
                            cost: number;
                            model: string;
                            prompt_tokens: number;
                            requests: number;
                            total_tokens: number;
                        }[];
                        by_provider: {
                            cost: number;
                            provider: string;
                            requests: number;
                            total_tokens: number;
                        }[];
                        total_cost: number;
                        total_requests: number;
                        total_tokens: number;
                        /** Format: uuid */
                        user_id: string;
                    };
                };
            };
        };
    };
    list_api_keys: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description default return */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        allowed_models?: string[] | null;
                        created_at: string;
                        expires_at?: string | null;
                        /** Format: uuid */
                        id: string;
                        is_active: boolean;
                        key: string;
                        last_used?: string | null;
                        name: string;
                        rate_limit_rpm?: number | null;
                    }[];
                };
            };
        };
    };
    create_api_key: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description API key creation request */
        requestBody: {
            content: {
                "application/json": {
                    allowed_models?: string[] | null;
                    expires_in_days?: number | null;
                    name: string;
                    rate_limit_rpm?: number | null;
                };
            };
        };
        responses: {
            /** @description default return */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        allowed_models?: string[] | null;
                        created_at: string;
                        expires_at?: string | null;
                        /** Format: uuid */
                        id: string;
                        is_active: boolean;
                        key: string;
                        last_used?: string | null;
                        name: string;
                        rate_limit_rpm?: number | null;
                    };
                };
            };
        };
    };
    revoke_api_key: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description default return */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": Record<string, never>;
                };
            };
        };
    };
    login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description User login request */
        requestBody: {
            content: {
                "application/json": {
                    email: string;
                    password: string;
                };
            };
        };
        responses: {
            /** @description default return */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        token: string;
                        user: {
                            created_at: string;
                            email: string;
                            /** Format: uuid */
                            id: string;
                            is_admin: boolean;
                            user_groups: string[];
                            username: string;
                        };
                    };
                };
            };
        };
    };
    logout: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description default return */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": Record<string, never>;
                };
            };
        };
    };
    refresh_token: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Refresh token request */
        requestBody: {
            content: {
                "application/json": {
                    refresh_token: string;
                };
            };
        };
        responses: {
            /** @description default return */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": Record<string, never>;
                };
            };
        };
    };
    register: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description User creation request */
        requestBody: {
            content: {
                "application/json": {
                    email: string;
                    password: string;
                    username: string;
                };
            };
        };
        responses: {
            /** @description default return */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        token: string;
                        user: {
                            created_at: string;
                            email: string;
                            /** Format: uuid */
                            id: string;
                            is_admin: boolean;
                            user_groups: string[];
                            username: string;
                        };
                    };
                };
            };
        };
    };
    validate_token: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description default return */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        user: {
                            created_at: string;
                            email: string;
                            /** Format: uuid */
                            id: string;
                            is_admin: boolean;
                            user_groups: string[];
                            username: string;
                        };
                    };
                };
            };
        };
    };
    health_check: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description default return */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        service: string;
                        status: string;
                        timestamp: string;
                    };
                };
            };
        };
    };
    list_available_models: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description default return */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        created_at: string;
                        display_name?: string | null;
                        /** Format: uuid */
                        id: string;
                        /** Format: decimal */
                        input_cost_per_1k?: string | null;
                        is_active: boolean;
                        max_context?: number | null;
                        model_id: string;
                        /** Format: decimal */
                        output_cost_per_1k?: string | null;
                        /** Format: uuid */
                        provider_config_id: string;
                        supports_tools: boolean;
                        supports_vision: boolean;
                        updated_at: string;
                    }[];
                };
            };
        };
    };
    get_usage: {
        parameters: {
            query?: {
                start?: string | null;
                end?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description default return */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** Format: uuid */
                        api_key_id?: string | null;
                        completion_tokens: number;
                        /** Format: decimal */
                        cost: string;
                        created_at: string;
                        /** Format: uuid */
                        id: string;
                        model: string;
                        prompt_tokens: number;
                        provider: string;
                        request_id: string;
                        total_tokens: number;
                        /** Format: uuid */
                        user_id: string;
                    }[];
                };
            };
        };
    };
    get_usage_stats: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description default return */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        active_keys: number;
                        total_cost: number;
                        total_requests: number;
                        total_tokens: number;
                    };
                };
            };
        };
    };
    get_current_user: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description default return */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        created_at: string;
                        email: string;
                        /** Format: uuid */
                        id: string;
                        is_admin: boolean;
                        user_groups: string[];
                        username: string;
                    };
                };
            };
        };
    };
    get_current_user: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description default return */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        created_at: string;
                        email: string;
                        /** Format: uuid */
                        id: string;
                        is_admin: boolean;
                        user_groups: string[];
                        username: string;
                    };
                };
            };
        };
    };
    update_profile: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Update profile request */
        requestBody: {
            content: {
                "application/json": {
                    username?: string | null;
                };
            };
        };
        responses: {
            /** @description default return */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        created_at: string;
                        email: string;
                        /** Format: uuid */
                        id: string;
                        is_admin: boolean;
                        user_groups: string[];
                        username: string;
                    };
                };
            };
        };
    };
}
