[basic]
host = "0.0.0.0"
port = 8080

[application.database]
url = "postgres://cafu:cafu@localhost/manti"
max_connections = 10

[application.auth]
jwt_secret = "change-me-in-production"
jwt_expiration = 86400  # 24 hours
